title: python-timestamps
hero_image: images/banner.png
subtitle: python-timestamps subtitle
description: python-timestamps description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Step one
    duration: 60
